<a href="https://colab.research.google.com/github/alwaysalearner1234/deep_learning/blob/main/loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


Implement Mean Absolute Error

In [5]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [6]:
import numpy as np

# Example actual and predicted values
y_true = np.array([10, 20, 30, 40])
y_predicted = np.array([12, 18, 33, 39])

# Define a function for Mean Absolute Error (MAE)
def mae(y_predicted, y_true):
    return np.mean(np.abs(y_predicted - y_true))

# Now call it
error = mae(y_predicted, y_true)
print("Mean Absolute Error:", error)


Mean Absolute Error: 2.0


In [7]:
mae(y_predicted, y_true)

np.float64(2.0)

Implement same thing using numpy in much easier way

In [8]:
np.abs(y_predicted-y_true)


array([2, 2, 3, 1])

In [9]:
np.mean(np.abs(y_predicted-y_true))

np.float64(2.0)

In [10]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [11]:
mae_np(y_predicted, y_true)

np.float64(2.0)

Implement Log Loss or Binary Cross Entropy


In [12]:
np.log([0])

/tmp/ipython-input-262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [13]:
epsilon = 1e-15

In [14]:
np.log([1e-15])

array([-34.53877639])

In [15]:
y_predicted

array([12, 18, 33, 39])

In [16]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(12), np.int64(18), np.int64(33), np.int64(39)]

In [17]:

1-epsilon

0.999999999999999

In [18]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0.999999999999999, 0.999999999999999]

In [19]:
y_predicted_new = np.array(y_predicted_new)

In [20]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -9.99200722e-16, -9.99200722e-16])

In [21]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(-828.9498238161812)

In [22]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [23]:
log_loss(y_true, y_predicted)

np.float64(-828.9498238161812)

Exercise
Implement mean squared error (or MSE) in two ways,

Without using numpy (i.e. using plain python)

With the use of numpy

In [24]:
# Mean Squared Error without using NumPy
def mse_plain(y_true, y_pred):
    # ensure both lists have same length
    n = len(y_true)
    squared_errors = [(y_pred[i] - y_true[i]) ** 2 for i in range(n)]
    mse = sum(squared_errors) / n
    return mse

# Example
y_true = [1, 2, 3, 4]
y_pred = [1.2, 1.9, 3.3, 3.8]

print("MSE (plain Python):", mse_plain(y_true, y_pred))


MSE (plain Python): 0.04499999999999999


In [25]:
import numpy as np

# Mean Squared Error using NumPy
def mse_numpy(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    mse = np.mean((y_pred - y_true) ** 2)
    return mse

# Example
y_true = [1, 2, 3, 4]
y_pred = [1.2, 1.9, 3.3, 3.8]

print("MSE (NumPy):", mse_numpy(y_true, y_pred))


MSE (NumPy): 0.04499999999999999
